import * as DocumentPicker from "expo-document-picker";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { usePlanner } from "@/src/app-context";
import { ActionButton, Icon } from "@/src/components/planner-ui";
import { uploadPlanPdf } from "@/src/import-api";
import { DraftTask, ImportedPlanDraft } from "@/src/plan-types";
import { makeStyles, useTheme } from "@/src/theme";

function rowIssues(task: DraftTask, all: DraftTask[]): string[] { const issues: string[] = []; if (!task.sprint || task.sprint < 1) issues.push("Sprint required"); if (!task.day || task.day < 1) issues.push("Day required"); if (!task.title.trim()) issues.push("Task title required"); if (!task.minutes || task.minutes < 1) issues.push("Minutes required"); if (all.filter((item) => item.sprint === task.sprint && item.day === task.day && item.title.trim().toLowerCase() === task.title.trim().toLowerCase()).length > 1) issues.push("Duplicate task"); return issues; }

export default function ImportPlanScreen() {
  const { saveImportedPlan } = usePlanner(); const { colors } = useTheme(); const styles = useStyles(); const insets = useSafeAreaInsets();
  const [draft, setDraft] = useState<ImportedPlanDraft | null>(null); const [name, setName] = useState(""); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const invalidRows = useMemo(() => draft?.tasks.filter((task) => rowIssues(task, draft.tasks).length).length ?? 0, [draft]);
  const pickPdf = async () => { setError(""); const result = await DocumentPicker.getDocumentAsync({ type: "application/pdf", copyToCacheDirectory: true, multiple: false }); if (result.canceled) return; setLoading(true); try { const next = await uploadPlanPdf(result.assets[0]); setDraft(next); setName(next.suggestedName); } catch (err) { setError(err instanceof Error ? err.message : "The PDF could not be imported."); } finally { setLoading(false); } };
  const updateTask = (index: number, patch: Partial<DraftTask>) => setDraft((current) => current ? { ...current, tasks: current.tasks.map((task, taskIndex) => taskIndex === index ? { ...task, ...patch } : task) } : current);
  const removeTask = (index: number) => setDraft((current) => current ? { ...current, tasks: current.tasks.filter((_, taskIndex) => taskIndex !== index) } : current);
  const addTask = () => setDraft((current) => current ? { ...current, tasks: [...current.tasks, { rowId: `manual-${Date.now()}`, sprint: 1, day: 1, title: "", minutes: 30 }] } : current);
  const save = async () => { if (!draft || invalidRows || !name?.trim()) return; setSaving(true); try { await saveImportedPlan(name, draft); router.replace("/plans"); } catch (err) { setError(err instanceof Error ? err.message : "Plan could not be saved."); } finally { setSaving(false); } };
  return <View style={styles.screen}><ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 28 }]} keyboardShouldPersistTaps="handled">
    <ActionButton testID="import-back-button" label="Back to plans" icon="arrow-left" secondary onPress={() => router.back()} />
    <View><Text style={styles.overline}>Aar Ya Paar / IMPORT</Text><Text style={styles.title}>{draft ? "Review plan" : "Import PDF plan"}</Text><Text style={styles.subtitle}>{draft ? "Check every row before saving. Your current plan remains unchanged." : "Choose a PDF using Sprint / Day / Task / Estimated Time tables."}</Text></View>
    {!draft ? <View style={styles.uploadCard}><Icon name="file-pdf-box" size={34} color={colors.brandPrimary} /><Text style={styles.uploadTitle}>Choose your study-plan PDF</Text><Text style={styles.uploadText}>We validate structured rows only—nothing is guessed.</Text><ActionButton testID="choose-pdf-button" label={loading ? "Reading PDF…" : "Choose PDF"} icon="folder-open-outline" onPress={() => void pickPdf()} disabled={loading} />{loading ? <ActivityIndicator color={colors.brandPrimary} /> : null}</View> : <Review draft={draft} name={name} setName={setName} updateTask={updateTask} removeTask={removeTask} addTask={addTask} invalidRows={invalidRows} onSave={() => void save()} saving={saving} />}
    {error ? <View testID="import-error" style={styles.error}><Icon name="alert-circle-outline" size={18} color={colors.error} /><Text style={styles.errorText}>{error}</Text></View> : null}
  </ScrollView></View>;
}
function Review({ draft, name, setName, updateTask, removeTask, addTask, invalidRows, onSave, saving }: { draft: ImportedPlanDraft; name: string; setName: (value: string) => void; updateTask: (index: number, patch: Partial<DraftTask>) => void; removeTask: (index: number) => void; addTask: () => void; invalidRows: number; onSave: () => void; saving: boolean }) {
  const styles = useStyles(); const { colors } = useTheme(); const safeName = name ?? ""; const total = draft.tasks.reduce((sum, task) => sum + (task.minutes ?? 0), 0); return <View style={styles.review}><View style={styles.summary}><Text style={styles.summaryValue}>{draft.tasks.length}</Text><Text style={styles.summaryLabel}>TASKS</Text><Text style={styles.summaryValue}>{total}m</Text><Text style={styles.summaryLabel}>TOTAL</Text></View><Text style={styles.label}>PLAN NAME</Text><TextInput testID="import-plan-name" value={safeName} onChangeText={setName} style={styles.nameInput} placeholder="Plan name" placeholderTextColor={colors.muted} />{draft.issues.map((issue) => <View key={issue} style={styles.warning}><Icon name="alert-outline" size={17} color={colors.warning} /><Text style={styles.warningText}>{issue}</Text></View>)}{invalidRows ? <View style={styles.warning}><Icon name="alert-outline" size={17} color={colors.warning} /><Text style={styles.warningText}>{invalidRows} rows need correction or removal before saving.</Text></View> : null}<Text style={styles.source}>SOURCE PDF · {draft.sourceFilename}</Text><View style={styles.rows}>{draft.tasks.map((task, index) => <EditableRow key={task.rowId} task={task} index={index} all={draft.tasks} updateTask={updateTask} removeTask={removeTask} />)}</View><ActionButton testID="add-import-task-button" label="Add task" icon="plus" secondary onPress={addTask} /><ActionButton testID="save-import-plan-button" label={saving ? "Saving plan…" : invalidRows ? "Resolve flagged rows to save" : "Save as new plan"} icon="content-save-outline" onPress={onSave} disabled={saving || Boolean(invalidRows) || !safeName.trim() || !draft.tasks.length} /></View>;
}
function EditableRow({ task, index, all, updateTask, removeTask }: { task: DraftTask; index: number; all: DraftTask[]; updateTask: (index: number, patch: Partial<DraftTask>) => void; removeTask: (index: number) => void }) { const styles = useStyles(); const { colors } = useTheme(); const issues = rowIssues(task, all); return <View testID={`import-task-${index}`} style={[styles.row, issues.length > 0 ? { borderColor: colors.warning } : null]}><View style={styles.rowHead}><Text style={styles.rowOrder}>#{index + 1}</Text><Pressable testID={`remove-import-task-${index}`} onPress={() => removeTask(index)}><Text style={styles.remove}>REMOVE</Text></Pressable></View><View style={styles.numberRow}><TextInput testID={`import-task-sprint-${index}`} value={task.sprint?.toString() ?? ""} onChangeText={(value) => updateTask(index, { sprint: Number(value) || null })} style={styles.smallInput} keyboardType="number-pad" placeholder="S" placeholderTextColor={colors.muted} /><TextInput testID={`import-task-day-${index}`} value={task.day?.toString() ?? ""} onChangeText={(value) => updateTask(index, { day: Number(value) || null })} style={styles.smallInput} keyboardType="number-pad" placeholder="D" placeholderTextColor={colors.muted} /><TextInput testID={`import-task-minutes-${index}`} value={task.minutes?.toString() ?? ""} onChangeText={(value) => updateTask(index, { minutes: Number(value) || null })} style={styles.minuteInput} keyboardType="number-pad" placeholder="MIN" placeholderTextColor={colors.muted} /></View><TextInput testID={`import-task-title-${index}`} value={task.title} onChangeText={(value) => updateTask(index, { title: value })} style={styles.taskInput} placeholder="Task title" placeholderTextColor={colors.muted} />{issues.length ? <Text style={styles.issue}>{issues.join(" · ")}</Text> : null}</View>; }
const useStyles = makeStyles((colors) => ({ screen: { flex: 1, backgroundColor: colors.surface }, content: { paddingHorizontal: 18, gap: 18 }, overline: { color: colors.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, title: { color: colors.onSurface, fontSize: 32, fontWeight: "900", marginTop: 4 }, subtitle: { color: colors.onSurfaceSecondary, fontSize: 14, lineHeight: 20, marginTop: 8 }, uploadCard: { borderWidth: 1, borderColor: colors.brandSecondary, backgroundColor: colors.brandTertiary, borderRadius: 14, padding: 22, alignItems: "center", gap: 12 }, uploadTitle: { color: colors.onSurface, fontSize: 18, fontWeight: "900", textAlign: "center" }, uploadText: { color: colors.onSurfaceSecondary, fontSize: 13, textAlign: "center", lineHeight: 19 }, error: { flexDirection: "row", gap: 8, padding: 12, borderRadius: 10, backgroundColor: colors.surfaceSecondary, borderWidth: 1, borderColor: colors.error }, errorText: { color: colors.error, flex: 1, fontSize: 13, lineHeight: 18 }, review: { gap: 12 }, summary: { flexDirection: "row", alignItems: "center", gap: 8, padding: 14, backgroundColor: colors.surfaceSecondary, borderRadius: 12, borderWidth: 1, borderColor: colors.border }, summaryValue: { color: colors.brandPrimary, fontSize: 18, fontWeight: "900" }, summaryLabel: { color: colors.muted, fontSize: 10, fontWeight: "900", marginRight: 10 }, label: { color: colors.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, nameInput: { height: 50, borderRadius: 10, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceSecondary, color: colors.onSurface, paddingHorizontal: 14, fontSize: 16, fontWeight: "700" }, warning: { flexDirection: "row", gap: 8, padding: 11, borderWidth: 1, borderColor: colors.warning, backgroundColor: colors.surfaceSecondary, borderRadius: 10 }, warningText: { color: colors.warning, flex: 1, fontSize: 12, lineHeight: 17 }, source: { color: colors.muted, fontSize: 10, fontWeight: "800", letterSpacing: 0.6 }, rows: { gap: 10 }, row: { backgroundColor: colors.surfaceSecondary, borderWidth: 1, borderColor: colors.border, padding: 12, borderRadius: 12, gap: 9 }, rowHead: { flexDirection: "row", justifyContent: "space-between" }, rowOrder: { color: colors.brandPrimary, fontWeight: "900", fontSize: 12 }, remove: { color: colors.error, fontSize: 10, fontWeight: "900" }, numberRow: { flexDirection: "row", gap: 8 }, smallInput: { width: 48, height: 38, textAlign: "center", color: colors.onSurface, backgroundColor: colors.surfaceTertiary, borderRadius: 7, fontWeight: "800" }, minuteInput: { flex: 1, height: 38, textAlign: "center", color: colors.onSurface, backgroundColor: colors.surfaceTertiary, borderRadius: 7, fontWeight: "800" }, taskInput: { minHeight: 44, color: colors.onSurface, backgroundColor: colors.surfaceTertiary, borderRadius: 7, paddingHorizontal: 10, fontWeight: "700" }, issue: { color: colors.warning, fontSize: 11, fontWeight: "700" } }));