import { router } from "expo-router";
import { Pressable, ScrollView, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { usePlanner } from "@/src/app-context";
import { ActionButton, Icon } from "@/src/components/planner-ui";
import { makeStyles, useTheme } from "@/src/theme";

export default function PlansScreen() {
  const { activePlanId, loading, plans, setActivePlan } = usePlanner(); const insets = useSafeAreaInsets(); const styles = useStyles(); const { colors } = useTheme();
  if (loading) return <View style={styles.center}><Text style={styles.muted}>Loading your plans…</Text></View>;
  return <View style={styles.screen}><ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 28 }]}>
    <ActionButton testID="plans-back-button" label="Back to planner" icon="arrow-left" secondary onPress={() => router.back()} />
    <View><Text style={styles.overline}>Aap Ya Paar / LIBRARY</Text><Text style={styles.title}>Study plans</Text><Text style={styles.subtitle}>Each plan keeps its own schedule, progress, and study settings.</Text></View>
    <ActionButton testID="import-pdf-plan-button" label="Import PDF plan" icon="file-pdf-box" onPress={() => router.push("/import-plan")} />
    <Text style={styles.note}>Your current plan stays unchanged until you save and make another plan active.</Text>
    <View style={styles.list}>{plans.map((plan) => { const active = plan.id === activePlanId; const complete = plan.state.completionRecords.length; return <Pressable key={plan.id} testID={`make-active-plan-card-${plan.id}`} accessibilityRole={active ? undefined : "button"} onPress={active ? undefined : () => void setActivePlan(plan.id)} style={({ pressed }) => [styles.card, active && { borderColor: colors.brandPrimary }, pressed && !active && styles.pressed]}><View style={styles.cardTop}><View style={styles.planIcon}><Icon name={active ? "check-circle" : "book-open-page-variant"} size={19} color={colors.brandPrimary} /></View><View style={styles.cardBody}><Text style={styles.planName}>{plan.name}</Text><Text style={styles.cardMeta}>{plan.state.tasks.length} tasks · {complete} complete</Text>{plan.sourceFilename ? <Text style={styles.source}>PDF · {plan.sourceFilename}</Text> : <Text style={styles.source}>Built-in curriculum</Text>}</View>{active ? <View style={styles.active}><Text style={styles.activeText}>ACTIVE</Text></View> : <View style={styles.activate}><Text style={styles.activateText}>TAP TO ACTIVATE</Text></View>}</View>{plan.importedAt ? <Text style={styles.date}>Imported {new Date(plan.importedAt).toLocaleDateString()}</Text> : null}</Pressable>; })}</View>
  </ScrollView></View>;
}
const useStyles = makeStyles((colors) => ({
  screen: { flex: 1, backgroundColor: colors.surface }, content: { paddingHorizontal: 18, gap: 18 }, center: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: colors.surface }, muted: { color: colors.muted }, overline: { color: colors.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, title: { color: colors.onSurface, fontSize: 32, fontWeight: "900", marginTop: 4 }, subtitle: { color: colors.onSurfaceSecondary, fontSize: 14, lineHeight: 20, marginTop: 8 }, note: { color: colors.onBrandTertiary, fontSize: 12, lineHeight: 18, borderWidth: 1, borderColor: colors.brandSecondary, backgroundColor: colors.brandTertiary, borderRadius: 10, padding: 12 }, list: { gap: 12 }, card: { backgroundColor: colors.surfaceSecondary, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 14, gap: 12 }, pressed: { opacity: 0.75 }, cardTop: { flexDirection: "row", alignItems: "center", gap: 11 }, planIcon: { width: 38, height: 38, borderRadius: 10, justifyContent: "center", alignItems: "center", backgroundColor: colors.brandTertiary }, cardBody: { flex: 1, gap: 3 }, planName: { color: colors.onSurface, fontSize: 16, fontWeight: "900" }, cardMeta: { color: colors.onSurfaceSecondary, fontSize: 12 }, source: { color: colors.muted, fontSize: 11 }, active: { paddingHorizontal: 7, paddingVertical: 5, borderRadius: 6, backgroundColor: colors.brandPrimary }, activeText: { color: colors.onBrandPrimary, fontSize: 9, fontWeight: "900" }, activate: { paddingHorizontal: 7, paddingVertical: 5, borderRadius: 6, backgroundColor: colors.surfaceTertiary, borderWidth: 1, borderColor: colors.border }, activateText: { color: colors.brandPrimary, fontSize: 8, fontWeight: "900" }, date: { color: colors.muted, fontSize: 10, marginTop: -4 },
}));