import { useEffect, useState } from "react";
import { router } from "expo-router";
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, Switch, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { usePlanner } from "@/src/app-context";
import { ActionButton, Icon, SectionTitle } from "@/src/components/planner-ui";
import { makeStyles, useTheme } from "@/src/theme";
import { usesNativeTabs } from "@/src/navigation";

export default function SettingsScreen() {
  const { state, updateSettings, exportData, importData, resetProgress } = usePlanner();
  const insets = useSafeAreaInsets();
  const styles = useStyles();
  const { colors } = useTheme();
  const [weekday, setWeekday] = useState(""); const [saturday, setSaturday] = useState(""); const [sunday, setSunday] = useState(""); const [reminder, setReminder] = useState(""); const [notifications, setNotifications] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { if (state) { setWeekday(String(state.settings.weekdayMinutes)); setSaturday(String(state.settings.saturdayMinutes)); setSunday(String(state.settings.sundayMinutes)); setReminder(state.settings.reminderTime); setNotifications(state.settings.notificationsEnabled); } }, [state]);
  if (!state) return <View style={styles.center}><Text style={styles.muted}>Loading settings…</Text></View>;
  const save = async () => { setSaving(true); await updateSettings({ weekdayMinutes: Math.max(15, Number(weekday) || 60), saturdayMinutes: Math.max(15, Number(saturday) || 240), sundayMinutes: Math.max(15, Number(sunday) || 240), reminderTime: reminder || "20:30", notificationsEnabled: notifications }); setSaving(false); Alert.alert("Schedule recalculated", "Your future sessions now reflect these settings."); };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === "ios" ? "padding" : "height"}><ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: 28 + (usesNativeTabs ? insets.bottom : 0) }]} keyboardShouldPersistTaps="handled">
    <View><Text style={styles.overline}>Aar Ya Paar / CONTROL ROOM</Text><Text style={styles.title}>Settings</Text><Text style={styles.subtitle}>Tune the plan without breaking the sequence.</Text></View>
    <SectionTitle eyebrow="CAPACITY" title="Daily minutes" />
    <View style={styles.card}><SettingInput label="WEEKDAYS" value={weekday} onChangeText={setWeekday} /><SettingInput label="SATURDAY" value={saturday} onChangeText={setSaturday} /><SettingInput label="SUNDAY" value={sunday} onChangeText={setSunday} /></View>
    <SectionTitle eyebrow="RHYTHM" title="Reminders" />
    <View style={styles.card}><View style={styles.row}><View style={styles.rowIcon}><Icon name="bell-outline" size={20} color={colors.brandPrimary} /></View><View style={styles.rowBody}><Text style={styles.rowTitle}>Daily reminder</Text><Text style={styles.rowText}>At your local time, every day</Text></View><Switch value={notifications} onValueChange={setNotifications} trackColor={{ false: colors.surfaceTertiary, true: colors.brandSecondary }} thumbColor={notifications ? colors.brandPrimary : colors.muted} /></View><View style={styles.divider} /><View style={styles.timeRow}><Text style={styles.inputLabel}>REMINDER TIME</Text><TextInput value={reminder} onChangeText={setReminder} style={styles.timeInput} keyboardType="numbers-and-punctuation" placeholder="20:30" placeholderTextColor={colors.muted} /></View></View>
    <ActionButton testID="settings-save" label={saving ? "Recalculating…" : "Save & recalculate"} icon="refresh" onPress={() => void save()} disabled={saving} />
    <SectionTitle eyebrow="PLANS" title="Study plan library" />
    <View style={styles.card}><View style={styles.row}><View style={styles.rowIcon}><Icon name="book-multiple-outline" size={20} color={colors.brandPrimary} /></View><View style={styles.rowBody}><Text style={styles.rowTitle}>Import or switch plans</Text><Text style={styles.rowText}>Keep each curriculum and its progress separate.</Text></View></View><ActionButton testID="open-plan-library-button" label="Open plan library" icon="arrow-right" secondary onPress={() => router.push("/plans")} /></View>
    <SectionTitle eyebrow="DATA" title="Local backup" />
    <View style={styles.backupRow}><Pressable testID="settings-export" onPress={() => void exportData()} style={({ pressed }) => [styles.backupButton, pressed && styles.pressed]}><Icon name="content-copy" size={18} color={colors.onSurface} /><Text style={styles.backupText}>Copy export</Text></Pressable><Pressable testID="settings-import" onPress={() => void importData()} style={({ pressed }) => [styles.backupButton, pressed && styles.pressed]}><Icon name="content-paste" size={18} color={colors.onSurface} /><Text style={styles.backupText}>Import</Text></Pressable></View>
    <View style={styles.danger}><View style={styles.rowBody}><Text style={styles.rowTitle}>Reset progress</Text><Text style={styles.rowText}>Remove completions, overrides, and settings.</Text></View><Pressable onPress={() => Alert.alert("Reset everything?", "This cannot be undone.", [{ text: "Cancel", style: "cancel" }, { text: "Reset", style: "destructive", onPress: () => void resetProgress() }])} style={styles.resetButton}><Text style={styles.resetText}>RESET</Text></Pressable></View>
    <Text style={styles.version}>SCHEDULE V{state.scheduleVersion}  ·  LAST RECALCULATED {new Date(state.lastRecalculatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</Text>
  </ScrollView></KeyboardAvoidingView>;
}

function SettingInput({ label, value, onChangeText }: { label: string; value: string; onChangeText: (value: string) => void }) { const styles = useStyles(); return <View style={styles.inputRow}><Text style={styles.inputLabel}>{label}</Text><View style={styles.inputBox}><TextInput testID={`settings-${label.toLowerCase()}`} value={value} onChangeText={onChangeText} keyboardType="number-pad" style={styles.capacityInput} maxLength={3} /><Text style={styles.unit}>MIN</Text></View></View>; }

const useStyles = makeStyles((colors) => ({
  screen: { flex: 1, backgroundColor: colors.surface }, content: { paddingHorizontal: 18, gap: 20 }, center: { flex: 1, backgroundColor: colors.surface, justifyContent: "center", alignItems: "center" }, muted: { color: colors.muted }, overline: { color: colors.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, title: { color: colors.onSurface, fontSize: 34, fontWeight: "900", marginTop: 3 }, subtitle: { color: colors.onSurfaceSecondary, fontSize: 14, marginTop: 7 }, card: { backgroundColor: colors.surfaceSecondary, borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 16 }, inputRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.divider }, inputLabel: { color: colors.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, inputBox: { flexDirection: "row", alignItems: "center", gap: 7 }, capacityInput: { width: 68, height: 42, borderRadius: 8, backgroundColor: colors.surfaceTertiary, color: colors.onSurface, fontSize: 17, fontWeight: "800", textAlign: "center" }, unit: { color: colors.muted, fontSize: 10, fontWeight: "900" }, row: { minHeight: 72, flexDirection: "row", alignItems: "center", gap: 12 }, rowIcon: { width: 36, height: 36, borderRadius: 10, backgroundColor: colors.brandTertiary, alignItems: "center", justifyContent: "center" }, rowBody: { flex: 1, gap: 4 }, rowTitle: { color: colors.onSurface, fontSize: 14, fontWeight: "800" }, rowText: { color: colors.muted, fontSize: 12 }, divider: { height: 1, backgroundColor: colors.divider }, timeRow: { minHeight: 64, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, timeInput: { width: 82, height: 40, backgroundColor: colors.surfaceTertiary, borderRadius: 8, color: colors.onSurface, textAlign: "center", fontWeight: "800", fontSize: 15 }, backupRow: { flexDirection: "row", gap: 10 }, backupButton: { flex: 1, minHeight: 52, borderRadius: 10, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceSecondary, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, backupText: { color: colors.onSurface, fontSize: 13, fontWeight: "800" }, pressed: { opacity: 0.75 }, danger: { flexDirection: "row", alignItems: "center", padding: 15, borderRadius: 12, borderWidth: 1, borderColor: colors.error, backgroundColor: colors.surfaceSecondary, gap: 12 }, resetButton: { minHeight: 40, justifyContent: "center", paddingHorizontal: 10 }, resetText: { color: colors.error, fontSize: 11, fontWeight: "900", letterSpacing: 0.7 }, version: { color: colors.muted, fontSize: 9, textAlign: "center", fontWeight: "800", letterSpacing: 0.5, paddingBottom: 6 },
}));